/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './arena.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../auth/auth.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../opponent-find/opponent-find.component';
import * as import12 from '../game-list/game-list.component';
import * as import13 from '../opponent-find/opponent-find.component.ngfactory';
import * as import14 from '../opponent-find/opponent-find.sevices';
import * as import15 from '../socketHanding/socket.service';
import * as import16 from '../game-list/game-list.component.ngfactory';
import * as import17 from '../game-list/game-list.services';
var renderType_ArenaComponent_Host:import0.RenderComponentType = (null as any);
class _View_ArenaComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ArenaComponent_0_4:import3.ArenaComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent_Host0,renderType_ArenaComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-arena',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ArenaComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ArenaComponent_0_4 = new import3.ArenaComponent(this.parentInjector.get(import8.AuthService));
    this._appEl_0.initComponent(this._ArenaComponent_0_4,[],compView_0);
    compView_0.create(this._ArenaComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ArenaComponent) && (0 === requestNodeIndex))) { return this._ArenaComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ArenaComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ArenaComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ArenaComponent_Host === (null as any))) { (renderType_ArenaComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ArenaComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ArenaComponentNgFactory:import10.ComponentFactory<import3.ArenaComponent> = new import10.ComponentFactory<import3.ArenaComponent>('my-arena',viewFactory_ArenaComponent_Host0,import3.ArenaComponent);
const styles_ArenaComponent:any[] = [];
var renderType_ArenaComponent:import0.RenderComponentType = (null as any);
class _View_ArenaComponent0 extends import1.AppView<import3.ArenaComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _OpponentComponentFind_7_4:import11.OpponentComponentFind;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _GameListcomponent_12_4:import12.GameListcomponent;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ArenaComponent0,renderType_ArenaComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-md-5');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h1',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'opponent-find',(null as any));
    this._appEl_7 = new import2.AppElement(7,2,this,this._el_7);
    var compView_7:any = import13.viewFactory_OpponentComponentFind0(this.viewUtils,this.injector(7),this._appEl_7);
    this._OpponentComponentFind_7_4 = new import11.OpponentComponentFind(this.parentInjector.get(import14.OpponentFindService),this.parentInjector.get(import15.SocketService));
    this._appEl_7.initComponent(this._OpponentComponentFind_7_4,[],compView_7);
    compView_7.create(this._OpponentComponentFind_7_4,[],(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-md-7');
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'game-list',(null as any));
    this._appEl_12 = new import2.AppElement(12,10,this,this._el_12);
    var compView_12:any = import16.viewFactory_GameListcomponent0(this.viewUtils,this.injector(12),this._appEl_12);
    this._GameListcomponent_12_4 = new import12.GameListcomponent(this.parentInjector.get(import17.GameListServices),this.parentInjector.get(import15.SocketService),this.parentInjector.get(import8.AuthService));
    this._appEl_12.initComponent(this._GameListcomponent_12_4,[],compView_12);
    compView_12.create(this._GameListcomponent_12_4,[],(null as any));
    this._text_13 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.OpponentComponentFind) && (7 === requestNodeIndex))) { return this._OpponentComponentFind_7_4; }
    if (((token === import12.GameListcomponent) && (12 === requestNodeIndex))) { return this._GameListcomponent_12_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OpponentComponentFind_7_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._GameListcomponent_12_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.userName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ArenaComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ArenaComponent> {
  if ((renderType_ArenaComponent === (null as any))) { (renderType_ArenaComponent = viewUtils.createRenderComponentType('C:/Users/alex/Desktop/nodeJs/Quiz/assets/app/MainApp/arena/arena.component.ts class ArenaComponent - inline template',0,import9.ViewEncapsulation.None,styles_ArenaComponent,{})); }
  return new _View_ArenaComponent0(viewUtils,parentInjector,declarationEl);
}