/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from '@angular/material/core/ripple/ripple';
import * as import10 from '@angular/material/button/button';
import * as import11 from '@angular/material/card/card';
import * as import12 from '@angular/material/checkbox/checkbox';
import * as import13 from '@angular/material/core/line/line';
import * as import14 from '@angular/material/grid-list/grid-list';
import * as import15 from '@angular/material/input/input';
import * as import16 from '@angular/material/list/list';
import * as import17 from '@angular/material/progress-bar/progress-bar';
import * as import18 from '@angular/material/progress-circle/progress-circle';
import * as import19 from '@angular/material/sidenav/sidenav';
import * as import20 from '@angular/material/core/portal/portal-directives';
import * as import21 from '@angular/material/tabs/tabs';
import * as import22 from '@angular/material/toolbar/toolbar';
import * as import23 from '@angular/material/core/rtl/dir';
import * as import24 from '@angular/material/core/a11y/index';
import * as import25 from '@angular/material/button-toggle/button-toggle';
import * as import26 from '@angular/material/core/overlay/overlay-directives';
import * as import27 from '@angular/material/dialog/dialog';
import * as import28 from '@angular/material/icon/icon';
import * as import29 from '@angular/material/menu/menu';
import * as import30 from '@angular/material/radio/radio';
import * as import31 from '@angular/material/slider/slider';
import * as import32 from '@angular/material/slide-toggle/slide-toggle';
import * as import33 from '@angular/material/snack-bar/snack-bar';
import * as import34 from '@angular/material/tooltip/tooltip';
import * as import35 from '@angular/material/core/compatibility/style-compatibility';
import * as import36 from '@angular/material/module';
import * as import37 from 'ng2-bs3-modal/ng2-bs3-modal';
import * as import38 from '@angular/common/src/localization';
import * as import39 from '@angular/core/src/application_init';
import * as import40 from '@angular/core/src/testability/testability';
import * as import41 from '@angular/core/src/application_ref';
import * as import42 from '@angular/core/src/linker/compiler';
import * as import43 from '@angular/material/core/gestures/MdGestureConfig';
import * as import44 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import45 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import46 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import47 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import48 from '@angular/core/src/linker/view_utils';
import * as import49 from '@angular/platform-browser/src/browser/title';
import * as import50 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import51 from '@angular/forms/src/form_builder';
import * as import52 from '@angular/http/src/backends/browser_xhr';
import * as import53 from '@angular/http/src/base_response_options';
import * as import54 from '@angular/http/src/backends/xhr_backend';
import * as import55 from '@angular/http/src/base_request_options';
import * as import56 from '@angular/material/core/a11y/live-announcer';
import * as import57 from '@angular/material/core/a11y/interactivity-checker';
import * as import58 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import59 from '@angular/material/core/overlay/overlay-container';
import * as import60 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import61 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import62 from '@angular/material/core/overlay/overlay';
import * as import63 from '@angular/material/icon/icon-registry';
import * as import64 from '@angular/common/src/location/location';
import * as import65 from '@angular/router/src/url_tree';
import * as import66 from '@angular/router/src/router_outlet_map';
import * as import67 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import68 from './auth/auth.service';
import * as import69 from './questions/question.service';
import * as import70 from './MainApp/game-list/game-list.services';
import * as import71 from './MainApp/socketHanding/socket.service';
import * as import72 from './MainApp/opponent-find/opponent-find.sevices';
import * as import73 from './questions/questionServices/arena.service';
import * as import74 from './questions/questionServices/question.service';
import * as import75 from './questions/questionServices/questionAnswer.service';
import * as import76 from '@angular/core/src/di/injector';
import * as import77 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import78 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import79 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import80 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import81 from './MainApp/main.component.ngfactory';
import * as import82 from './MainApp/arena/arena.component.ngfactory';
import * as import83 from './questions/question-structure.component.ngfactory';
import * as import84 from './auth/authentication.component.ngfactory';
import * as import85 from './auth/signup.component.ngfactory';
import * as import86 from './auth/login.component.ngfactory';
import * as import87 from './auth/logout.component.ngfactory';
import * as import88 from './app.component.ngfactory';
import * as import89 from '@angular/core/src/application_tokens';
import * as import90 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import91 from '@angular/platform-browser/src/dom/events/key_events';
import * as import92 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import93 from '@angular/core/src/zone/ng_zone';
import * as import94 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import95 from '@angular/common/src/location/platform_location';
import * as import96 from '@angular/common/src/location/location_strategy';
import * as import97 from './MainApp/main.component';
import * as import98 from './MainApp/arena/arena.component';
import * as import99 from './questions/question-structure.component';
import * as import100 from './auth/authentication.component';
import * as import101 from './auth/signup.component';
import * as import102 from './auth/login.component';
import * as import103 from './auth/logout.component';
import * as import104 from '@angular/router/src/router';
import * as import105 from '@angular/core/src/console';
import * as import106 from '@angular/core/src/i18n/tokens';
import * as import107 from '@angular/core/src/error_handler';
import * as import108 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import109 from '@angular/platform-browser/src/dom/animation_driver';
import * as import110 from '@angular/core/src/render/api';
import * as import111 from '@angular/core/src/security';
import * as import112 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import113 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import114 from '@angular/http/src/interfaces';
import * as import115 from '@angular/http/src/http';
import * as import116 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import117 from '@angular/router/src/router_config_loader';
import * as import118 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _ReactiveFormsModule_7:import6.ReactiveFormsModule;
  _HttpModule_8:import8.HttpModule;
  _MdRippleModule_9:import9.MdRippleModule;
  _MdButtonModule_10:import10.MdButtonModule;
  _MdCardModule_11:import11.MdCardModule;
  _MdCheckboxModule_12:import12.MdCheckboxModule;
  _MdLineModule_13:import13.MdLineModule;
  _MdGridListModule_14:import14.MdGridListModule;
  _MdInputModule_15:import15.MdInputModule;
  _MdListModule_16:import16.MdListModule;
  _MdProgressBarModule_17:import17.MdProgressBarModule;
  _MdProgressCircleModule_18:import18.MdProgressCircleModule;
  _MdSidenavModule_19:import19.MdSidenavModule;
  _PortalModule_20:import20.PortalModule;
  _MdTabsModule_21:import21.MdTabsModule;
  _MdToolbarModule_22:import22.MdToolbarModule;
  _RtlModule_23:import23.RtlModule;
  _A11yModule_24:import24.A11yModule;
  _MdButtonToggleModule_25:import25.MdButtonToggleModule;
  _OverlayModule_26:import26.OverlayModule;
  _MdDialogModule_27:import27.MdDialogModule;
  _MdIconModule_28:import28.MdIconModule;
  _MdMenuModule_29:import29.MdMenuModule;
  _MdRadioModule_30:import30.MdRadioModule;
  _MdSliderModule_31:import31.MdSliderModule;
  _MdSlideToggleModule_32:import32.MdSlideToggleModule;
  _MdSnackBarModule_33:import33.MdSnackBarModule;
  _MdTooltipModule_34:import34.MdTooltipModule;
  _StyleCompatibilityModule_35:import35.StyleCompatibilityModule;
  _MaterialRootModule_36:import36.MaterialRootModule;
  _Ng2Bs3ModalModule_37:import37.Ng2Bs3ModalModule;
  _AppModule_38:import1.AppModule;
  __LOCALE_ID_39:any;
  __NgLocalization_40:import38.NgLocaleLocalization;
  _ErrorHandler_41:any;
  _ApplicationInitStatus_42:import39.ApplicationInitStatus;
  _Testability_43:import40.Testability;
  _ApplicationRef__44:import41.ApplicationRef_;
  __ApplicationRef_45:any;
  __Compiler_46:import42.Compiler;
  __APP_ID_47:any;
  __DOCUMENT_48:any;
  __HAMMER_GESTURE_CONFIG_49:import43.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_50:any[];
  __EventManager_51:import44.EventManager;
  __DomSharedStylesHost_52:import45.DomSharedStylesHost;
  __AnimationDriver_53:any;
  __DomRootRenderer_54:import46.DomRootRenderer_;
  __RootRenderer_55:any;
  __DomSanitizer_56:import47.DomSanitizerImpl;
  __Sanitizer_57:any;
  __ViewUtils_58:import48.ViewUtils;
  __IterableDiffers_59:any;
  __KeyValueDiffers_60:any;
  __SharedStylesHost_61:any;
  __Title_62:import49.Title;
  __RadioControlRegistry_63:import50.RadioControlRegistry;
  __FormBuilder_64:import51.FormBuilder;
  __BrowserXhr_65:import52.BrowserXhr;
  __ResponseOptions_66:import53.BaseResponseOptions;
  __XSRFStrategy_67:any;
  __XHRBackend_68:import54.XHRBackend;
  __RequestOptions_69:import55.BaseRequestOptions;
  __Http_70:any;
  __MdLiveAnnouncer_71:import56.MdLiveAnnouncer;
  __InteractivityChecker_72:import57.InteractivityChecker;
  __MdUniqueSelectionDispatcher_73:import58.MdUniqueSelectionDispatcher;
  __OverlayContainer_74:import59.OverlayContainer;
  __ViewportRuler_75:import60.ViewportRuler;
  __OverlayPositionBuilder_76:import61.OverlayPositionBuilder;
  __Overlay_77:import62.Overlay;
  __MdDialog_78:import27.MdDialog;
  __MdIconRegistry_79:import63.MdIconRegistry;
  __MdSnackBar_80:import33.MdSnackBar;
  __ROUTER_CONFIGURATION_81:any;
  __LocationStrategy_82:any;
  __Location_83:import64.Location;
  __UrlSerializer_84:import65.DefaultUrlSerializer;
  __RouterOutletMap_85:import66.RouterOutletMap;
  __NgModuleFactoryLoader_86:import67.SystemJsNgModuleLoader;
  __ROUTES_87:any[];
  __Router_88:any;
  __ActivatedRoute_89:any;
  __APP_BOOTSTRAP_LISTENER_90:any[];
  __AuthService_91:import68.AuthService;
  __QuestionService_92:import69.QuestionService;
  __GameListServices_93:import70.GameListServices;
  __SocketService_94:import71.SocketService;
  __OpponentFindService_95:import72.OpponentFindService;
  __ArenaServices_96:import73.ArenaServices;
  __QuestionServices_97:import74.QuestionServices;
  __QuestionAnswerServices_98:import75.QuestionAnswerServices;
  constructor(parent:import76.Injector) {
    super(parent,[
      import77.MdDialogContainerNgFactory,
      import78.MdSnackBarContainerNgFactory,
      import79.SimpleSnackBarNgFactory,
      import80.TooltipComponentNgFactory,
      import81.MainComponentNgFactory,
      import82.ArenaComponentNgFactory,
      import83.QuestionStructureNgFactory,
      import83.QuestionStructureNgFactory,
      import84.AuthenticationComponentNgFactory,
      import85.SignUpComponentNgFactory,
      import86.LoginComponentNgFactory,
      import87.LogoutComponentNgFactory,
      import88.AppComponentNgFactory
    ]
    ,[import88.AppComponentNgFactory]);
  }
  get _LOCALE_ID_39():any {
    if ((this.__LOCALE_ID_39 == (null as any))) { (this.__LOCALE_ID_39 = 'en-US'); }
    return this.__LOCALE_ID_39;
  }
  get _NgLocalization_40():import38.NgLocaleLocalization {
    if ((this.__NgLocalization_40 == (null as any))) { (this.__NgLocalization_40 = new import38.NgLocaleLocalization(this._LOCALE_ID_39)); }
    return this.__NgLocalization_40;
  }
  get _ApplicationRef_45():any {
    if ((this.__ApplicationRef_45 == (null as any))) { (this.__ApplicationRef_45 = this._ApplicationRef__44); }
    return this.__ApplicationRef_45;
  }
  get _Compiler_46():import42.Compiler {
    if ((this.__Compiler_46 == (null as any))) { (this.__Compiler_46 = new import42.Compiler()); }
    return this.__Compiler_46;
  }
  get _APP_ID_47():any {
    if ((this.__APP_ID_47 == (null as any))) { (this.__APP_ID_47 = import89._appIdRandomProviderFactory()); }
    return this.__APP_ID_47;
  }
  get _DOCUMENT_48():any {
    if ((this.__DOCUMENT_48 == (null as any))) { (this.__DOCUMENT_48 = import4._document()); }
    return this.__DOCUMENT_48;
  }
  get _HAMMER_GESTURE_CONFIG_49():import43.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_49 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_49 = new import43.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_49;
  }
  get _EVENT_MANAGER_PLUGINS_50():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_50 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_50 = [
      new import90.DomEventsPlugin(),
      new import91.KeyEventsPlugin(),
      new import92.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_49)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_50;
  }
  get _EventManager_51():import44.EventManager {
    if ((this.__EventManager_51 == (null as any))) { (this.__EventManager_51 = new import44.EventManager(this._EVENT_MANAGER_PLUGINS_50,this.parent.get(import93.NgZone))); }
    return this.__EventManager_51;
  }
  get _DomSharedStylesHost_52():import45.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_52 == (null as any))) { (this.__DomSharedStylesHost_52 = new import45.DomSharedStylesHost(this._DOCUMENT_48)); }
    return this.__DomSharedStylesHost_52;
  }
  get _AnimationDriver_53():any {
    if ((this.__AnimationDriver_53 == (null as any))) { (this.__AnimationDriver_53 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_53;
  }
  get _DomRootRenderer_54():import46.DomRootRenderer_ {
    if ((this.__DomRootRenderer_54 == (null as any))) { (this.__DomRootRenderer_54 = new import46.DomRootRenderer_(this._DOCUMENT_48,this._EventManager_51,this._DomSharedStylesHost_52,this._AnimationDriver_53)); }
    return this.__DomRootRenderer_54;
  }
  get _RootRenderer_55():any {
    if ((this.__RootRenderer_55 == (null as any))) { (this.__RootRenderer_55 = import94._createConditionalRootRenderer(this._DomRootRenderer_54,this.parent.get(import94.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_55;
  }
  get _DomSanitizer_56():import47.DomSanitizerImpl {
    if ((this.__DomSanitizer_56 == (null as any))) { (this.__DomSanitizer_56 = new import47.DomSanitizerImpl()); }
    return this.__DomSanitizer_56;
  }
  get _Sanitizer_57():any {
    if ((this.__Sanitizer_57 == (null as any))) { (this.__Sanitizer_57 = this._DomSanitizer_56); }
    return this.__Sanitizer_57;
  }
  get _ViewUtils_58():import48.ViewUtils {
    if ((this.__ViewUtils_58 == (null as any))) { (this.__ViewUtils_58 = new import48.ViewUtils(this._RootRenderer_55,this._APP_ID_47,this._Sanitizer_57)); }
    return this.__ViewUtils_58;
  }
  get _IterableDiffers_59():any {
    if ((this.__IterableDiffers_59 == (null as any))) { (this.__IterableDiffers_59 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_59;
  }
  get _KeyValueDiffers_60():any {
    if ((this.__KeyValueDiffers_60 == (null as any))) { (this.__KeyValueDiffers_60 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_60;
  }
  get _SharedStylesHost_61():any {
    if ((this.__SharedStylesHost_61 == (null as any))) { (this.__SharedStylesHost_61 = this._DomSharedStylesHost_52); }
    return this.__SharedStylesHost_61;
  }
  get _Title_62():import49.Title {
    if ((this.__Title_62 == (null as any))) { (this.__Title_62 = new import49.Title()); }
    return this.__Title_62;
  }
  get _RadioControlRegistry_63():import50.RadioControlRegistry {
    if ((this.__RadioControlRegistry_63 == (null as any))) { (this.__RadioControlRegistry_63 = new import50.RadioControlRegistry()); }
    return this.__RadioControlRegistry_63;
  }
  get _FormBuilder_64():import51.FormBuilder {
    if ((this.__FormBuilder_64 == (null as any))) { (this.__FormBuilder_64 = new import51.FormBuilder()); }
    return this.__FormBuilder_64;
  }
  get _BrowserXhr_65():import52.BrowserXhr {
    if ((this.__BrowserXhr_65 == (null as any))) { (this.__BrowserXhr_65 = new import52.BrowserXhr()); }
    return this.__BrowserXhr_65;
  }
  get _ResponseOptions_66():import53.BaseResponseOptions {
    if ((this.__ResponseOptions_66 == (null as any))) { (this.__ResponseOptions_66 = new import53.BaseResponseOptions()); }
    return this.__ResponseOptions_66;
  }
  get _XSRFStrategy_67():any {
    if ((this.__XSRFStrategy_67 == (null as any))) { (this.__XSRFStrategy_67 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_67;
  }
  get _XHRBackend_68():import54.XHRBackend {
    if ((this.__XHRBackend_68 == (null as any))) { (this.__XHRBackend_68 = new import54.XHRBackend(this._BrowserXhr_65,this._ResponseOptions_66,this._XSRFStrategy_67)); }
    return this.__XHRBackend_68;
  }
  get _RequestOptions_69():import55.BaseRequestOptions {
    if ((this.__RequestOptions_69 == (null as any))) { (this.__RequestOptions_69 = new import55.BaseRequestOptions()); }
    return this.__RequestOptions_69;
  }
  get _Http_70():any {
    if ((this.__Http_70 == (null as any))) { (this.__Http_70 = import8.httpFactory(this._XHRBackend_68,this._RequestOptions_69)); }
    return this.__Http_70;
  }
  get _MdLiveAnnouncer_71():import56.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_71 == (null as any))) { (this.__MdLiveAnnouncer_71 = new import56.MdLiveAnnouncer(this.parent.get(import56.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_71;
  }
  get _InteractivityChecker_72():import57.InteractivityChecker {
    if ((this.__InteractivityChecker_72 == (null as any))) { (this.__InteractivityChecker_72 = new import57.InteractivityChecker()); }
    return this.__InteractivityChecker_72;
  }
  get _MdUniqueSelectionDispatcher_73():import58.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_73 == (null as any))) { (this.__MdUniqueSelectionDispatcher_73 = new import58.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_73;
  }
  get _OverlayContainer_74():import59.OverlayContainer {
    if ((this.__OverlayContainer_74 == (null as any))) { (this.__OverlayContainer_74 = new import59.OverlayContainer()); }
    return this.__OverlayContainer_74;
  }
  get _ViewportRuler_75():import60.ViewportRuler {
    if ((this.__ViewportRuler_75 == (null as any))) { (this.__ViewportRuler_75 = new import60.ViewportRuler()); }
    return this.__ViewportRuler_75;
  }
  get _OverlayPositionBuilder_76():import61.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_76 == (null as any))) { (this.__OverlayPositionBuilder_76 = new import61.OverlayPositionBuilder(this._ViewportRuler_75)); }
    return this.__OverlayPositionBuilder_76;
  }
  get _Overlay_77():import62.Overlay {
    if ((this.__Overlay_77 == (null as any))) { (this.__Overlay_77 = new import62.Overlay(this._OverlayContainer_74,this,this._OverlayPositionBuilder_76,this._ApplicationRef_45,this)); }
    return this.__Overlay_77;
  }
  get _MdDialog_78():import27.MdDialog {
    if ((this.__MdDialog_78 == (null as any))) { (this.__MdDialog_78 = new import27.MdDialog(this._Overlay_77,this)); }
    return this.__MdDialog_78;
  }
  get _MdIconRegistry_79():import63.MdIconRegistry {
    if ((this.__MdIconRegistry_79 == (null as any))) { (this.__MdIconRegistry_79 = new import63.MdIconRegistry(this._Http_70)); }
    return this.__MdIconRegistry_79;
  }
  get _MdSnackBar_80():import33.MdSnackBar {
    if ((this.__MdSnackBar_80 == (null as any))) { (this.__MdSnackBar_80 = new import33.MdSnackBar(this._Overlay_77,this._MdLiveAnnouncer_71)); }
    return this.__MdSnackBar_80;
  }
  get _ROUTER_CONFIGURATION_81():any {
    if ((this.__ROUTER_CONFIGURATION_81 == (null as any))) { (this.__ROUTER_CONFIGURATION_81 = {}); }
    return this.__ROUTER_CONFIGURATION_81;
  }
  get _LocationStrategy_82():any {
    if ((this.__LocationStrategy_82 == (null as any))) { (this.__LocationStrategy_82 = import7.provideLocationStrategy(this.parent.get(import95.PlatformLocation),this.parent.get(import96.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_81)); }
    return this.__LocationStrategy_82;
  }
  get _Location_83():import64.Location {
    if ((this.__Location_83 == (null as any))) { (this.__Location_83 = new import64.Location(this._LocationStrategy_82)); }
    return this.__Location_83;
  }
  get _UrlSerializer_84():import65.DefaultUrlSerializer {
    if ((this.__UrlSerializer_84 == (null as any))) { (this.__UrlSerializer_84 = new import65.DefaultUrlSerializer()); }
    return this.__UrlSerializer_84;
  }
  get _RouterOutletMap_85():import66.RouterOutletMap {
    if ((this.__RouterOutletMap_85 == (null as any))) { (this.__RouterOutletMap_85 = new import66.RouterOutletMap()); }
    return this.__RouterOutletMap_85;
  }
  get _NgModuleFactoryLoader_86():import67.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_86 == (null as any))) { (this.__NgModuleFactoryLoader_86 = new import67.SystemJsNgModuleLoader(this._Compiler_46,this.parent.get(import67.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_86;
  }
  get _ROUTES_87():any[] {
      if ((this.__ROUTES_87 == (null as any))) { (this.__ROUTES_87 = [[
        {
          path: '',
          redirectTo: 'mainApp',
          pathMatch: 'full'
        }
        ,
        {
          path: 'mainApp',
          component: import97.MainComponent,
          children: [
            {
              path: '',
              redirectTo: 'arena',
              pathMatch: 'full'
            }
            ,
            {
              path: 'arena',
              component: import98.ArenaComponent
            }
            ,
            {
              path: 'arena/:id',
              component: import99.QuestionStructure
            }

          ]

        }
        ,
        {
          path: 'questions',
          component: import99.QuestionStructure
        }
        ,
        {
          path: 'auth',
          component: import100.AuthenticationComponent,
          children: [
            {
              path: '',
              redirectTo: 'signup',
              pathMatch: 'full'
            }
            ,
            {
              path: 'signup',
              component: import101.SignUpComponent
            }
            ,
            {
              path: 'signin',
              component: import102.LoginComponent
            }
            ,
            {
              path: 'logout',
              component: import103.LogoutComponent
            }

          ]

        }

      ]
    ]); }
    return this.__ROUTES_87;
  }
  get _Router_88():any {
    if ((this.__Router_88 == (null as any))) { (this.__Router_88 = import7.setupRouter(this._ApplicationRef_45,this._UrlSerializer_84,this._RouterOutletMap_85,this._Location_83,this,this._NgModuleFactoryLoader_86,this._Compiler_46,this._ROUTES_87,this._ROUTER_CONFIGURATION_81)); }
    return this.__Router_88;
  }
  get _ActivatedRoute_89():any {
    if ((this.__ActivatedRoute_89 == (null as any))) { (this.__ActivatedRoute_89 = import7.rootRoute(this._Router_88)); }
    return this.__ActivatedRoute_89;
  }
  get _APP_BOOTSTRAP_LISTENER_90():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_90 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_90 = [import7.initialRouterNavigation(this._Router_88,this._ROUTER_CONFIGURATION_81)]); }
    return this.__APP_BOOTSTRAP_LISTENER_90;
  }
  get _AuthService_91():import68.AuthService {
    if ((this.__AuthService_91 == (null as any))) { (this.__AuthService_91 = new import68.AuthService(this._Http_70)); }
    return this.__AuthService_91;
  }
  get _QuestionService_92():import69.QuestionService {
    if ((this.__QuestionService_92 == (null as any))) { (this.__QuestionService_92 = new import69.QuestionService(this._Http_70)); }
    return this.__QuestionService_92;
  }
  get _GameListServices_93():import70.GameListServices {
    if ((this.__GameListServices_93 == (null as any))) { (this.__GameListServices_93 = new import70.GameListServices(this._Http_70)); }
    return this.__GameListServices_93;
  }
  get _SocketService_94():import71.SocketService {
    if ((this.__SocketService_94 == (null as any))) { (this.__SocketService_94 = new import71.SocketService(this._GameListServices_93)); }
    return this.__SocketService_94;
  }
  get _OpponentFindService_95():import72.OpponentFindService {
    if ((this.__OpponentFindService_95 == (null as any))) { (this.__OpponentFindService_95 = new import72.OpponentFindService(this._Http_70,this._GameListServices_93)); }
    return this.__OpponentFindService_95;
  }
  get _ArenaServices_96():import73.ArenaServices {
    if ((this.__ArenaServices_96 == (null as any))) { (this.__ArenaServices_96 = new import73.ArenaServices(this._Http_70)); }
    return this.__ArenaServices_96;
  }
  get _QuestionServices_97():import74.QuestionServices {
    if ((this.__QuestionServices_97 == (null as any))) { (this.__QuestionServices_97 = new import74.QuestionServices(this._Http_70)); }
    return this.__QuestionServices_97;
  }
  get _QuestionAnswerServices_98():import75.QuestionAnswerServices {
    if ((this.__QuestionAnswerServices_98 == (null as any))) { (this.__QuestionAnswerServices_98 = new import75.QuestionAnswerServices(this._Http_70)); }
    return this.__QuestionAnswerServices_98;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import104.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._ReactiveFormsModule_7 = new import6.ReactiveFormsModule();
    this._HttpModule_8 = new import8.HttpModule();
    this._MdRippleModule_9 = new import9.MdRippleModule();
    this._MdButtonModule_10 = new import10.MdButtonModule();
    this._MdCardModule_11 = new import11.MdCardModule();
    this._MdCheckboxModule_12 = new import12.MdCheckboxModule();
    this._MdLineModule_13 = new import13.MdLineModule();
    this._MdGridListModule_14 = new import14.MdGridListModule();
    this._MdInputModule_15 = new import15.MdInputModule();
    this._MdListModule_16 = new import16.MdListModule();
    this._MdProgressBarModule_17 = new import17.MdProgressBarModule();
    this._MdProgressCircleModule_18 = new import18.MdProgressCircleModule();
    this._MdSidenavModule_19 = new import19.MdSidenavModule();
    this._PortalModule_20 = new import20.PortalModule();
    this._MdTabsModule_21 = new import21.MdTabsModule();
    this._MdToolbarModule_22 = new import22.MdToolbarModule();
    this._RtlModule_23 = new import23.RtlModule();
    this._A11yModule_24 = new import24.A11yModule();
    this._MdButtonToggleModule_25 = new import25.MdButtonToggleModule();
    this._OverlayModule_26 = new import26.OverlayModule();
    this._MdDialogModule_27 = new import27.MdDialogModule();
    this._MdIconModule_28 = new import28.MdIconModule();
    this._MdMenuModule_29 = new import29.MdMenuModule();
    this._MdRadioModule_30 = new import30.MdRadioModule();
    this._MdSliderModule_31 = new import31.MdSliderModule();
    this._MdSlideToggleModule_32 = new import32.MdSlideToggleModule();
    this._MdSnackBarModule_33 = new import33.MdSnackBarModule();
    this._MdTooltipModule_34 = new import34.MdTooltipModule();
    this._StyleCompatibilityModule_35 = new import35.StyleCompatibilityModule();
    this._MaterialRootModule_36 = new import36.MaterialRootModule();
    this._Ng2Bs3ModalModule_37 = new import37.Ng2Bs3ModalModule();
    this._AppModule_38 = new import1.AppModule();
    this._ErrorHandler_41 = import4.errorHandler();
    this._ApplicationInitStatus_42 = new import39.ApplicationInitStatus(this.parent.get(import39.APP_INITIALIZER,(null as any)));
    this._Testability_43 = new import40.Testability(this.parent.get(import93.NgZone));
    this._ApplicationRef__44 = new import41.ApplicationRef_(this.parent.get(import93.NgZone),this.parent.get(import105.Console),this,this._ErrorHandler_41,this,this._ApplicationInitStatus_42,this.parent.get(import40.TestabilityRegistry,(null as any)),this._Testability_43);
    return this._AppModule_38;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import8.HttpModule)) { return this._HttpModule_8; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_9; }
    if ((token === import10.MdButtonModule)) { return this._MdButtonModule_10; }
    if ((token === import11.MdCardModule)) { return this._MdCardModule_11; }
    if ((token === import12.MdCheckboxModule)) { return this._MdCheckboxModule_12; }
    if ((token === import13.MdLineModule)) { return this._MdLineModule_13; }
    if ((token === import14.MdGridListModule)) { return this._MdGridListModule_14; }
    if ((token === import15.MdInputModule)) { return this._MdInputModule_15; }
    if ((token === import16.MdListModule)) { return this._MdListModule_16; }
    if ((token === import17.MdProgressBarModule)) { return this._MdProgressBarModule_17; }
    if ((token === import18.MdProgressCircleModule)) { return this._MdProgressCircleModule_18; }
    if ((token === import19.MdSidenavModule)) { return this._MdSidenavModule_19; }
    if ((token === import20.PortalModule)) { return this._PortalModule_20; }
    if ((token === import21.MdTabsModule)) { return this._MdTabsModule_21; }
    if ((token === import22.MdToolbarModule)) { return this._MdToolbarModule_22; }
    if ((token === import23.RtlModule)) { return this._RtlModule_23; }
    if ((token === import24.A11yModule)) { return this._A11yModule_24; }
    if ((token === import25.MdButtonToggleModule)) { return this._MdButtonToggleModule_25; }
    if ((token === import26.OverlayModule)) { return this._OverlayModule_26; }
    if ((token === import27.MdDialogModule)) { return this._MdDialogModule_27; }
    if ((token === import28.MdIconModule)) { return this._MdIconModule_28; }
    if ((token === import29.MdMenuModule)) { return this._MdMenuModule_29; }
    if ((token === import30.MdRadioModule)) { return this._MdRadioModule_30; }
    if ((token === import31.MdSliderModule)) { return this._MdSliderModule_31; }
    if ((token === import32.MdSlideToggleModule)) { return this._MdSlideToggleModule_32; }
    if ((token === import33.MdSnackBarModule)) { return this._MdSnackBarModule_33; }
    if ((token === import34.MdTooltipModule)) { return this._MdTooltipModule_34; }
    if ((token === import35.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_35; }
    if ((token === import36.MaterialRootModule)) { return this._MaterialRootModule_36; }
    if ((token === import37.Ng2Bs3ModalModule)) { return this._Ng2Bs3ModalModule_37; }
    if ((token === import1.AppModule)) { return this._AppModule_38; }
    if ((token === import106.LOCALE_ID)) { return this._LOCALE_ID_39; }
    if ((token === import38.NgLocalization)) { return this._NgLocalization_40; }
    if ((token === import107.ErrorHandler)) { return this._ErrorHandler_41; }
    if ((token === import39.ApplicationInitStatus)) { return this._ApplicationInitStatus_42; }
    if ((token === import40.Testability)) { return this._Testability_43; }
    if ((token === import41.ApplicationRef_)) { return this._ApplicationRef__44; }
    if ((token === import41.ApplicationRef)) { return this._ApplicationRef_45; }
    if ((token === import42.Compiler)) { return this._Compiler_46; }
    if ((token === import89.APP_ID)) { return this._APP_ID_47; }
    if ((token === import108.DOCUMENT)) { return this._DOCUMENT_48; }
    if ((token === import92.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_49; }
    if ((token === import44.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_50; }
    if ((token === import44.EventManager)) { return this._EventManager_51; }
    if ((token === import45.DomSharedStylesHost)) { return this._DomSharedStylesHost_52; }
    if ((token === import109.AnimationDriver)) { return this._AnimationDriver_53; }
    if ((token === import46.DomRootRenderer)) { return this._DomRootRenderer_54; }
    if ((token === import110.RootRenderer)) { return this._RootRenderer_55; }
    if ((token === import47.DomSanitizer)) { return this._DomSanitizer_56; }
    if ((token === import111.Sanitizer)) { return this._Sanitizer_57; }
    if ((token === import48.ViewUtils)) { return this._ViewUtils_58; }
    if ((token === import112.IterableDiffers)) { return this._IterableDiffers_59; }
    if ((token === import113.KeyValueDiffers)) { return this._KeyValueDiffers_60; }
    if ((token === import45.SharedStylesHost)) { return this._SharedStylesHost_61; }
    if ((token === import49.Title)) { return this._Title_62; }
    if ((token === import50.RadioControlRegistry)) { return this._RadioControlRegistry_63; }
    if ((token === import51.FormBuilder)) { return this._FormBuilder_64; }
    if ((token === import52.BrowserXhr)) { return this._BrowserXhr_65; }
    if ((token === import53.ResponseOptions)) { return this._ResponseOptions_66; }
    if ((token === import114.XSRFStrategy)) { return this._XSRFStrategy_67; }
    if ((token === import54.XHRBackend)) { return this._XHRBackend_68; }
    if ((token === import55.RequestOptions)) { return this._RequestOptions_69; }
    if ((token === import115.Http)) { return this._Http_70; }
    if ((token === import56.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_71; }
    if ((token === import57.InteractivityChecker)) { return this._InteractivityChecker_72; }
    if ((token === import58.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_73; }
    if ((token === import59.OverlayContainer)) { return this._OverlayContainer_74; }
    if ((token === import60.ViewportRuler)) { return this._ViewportRuler_75; }
    if ((token === import61.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_76; }
    if ((token === import62.Overlay)) { return this._Overlay_77; }
    if ((token === import27.MdDialog)) { return this._MdDialog_78; }
    if ((token === import63.MdIconRegistry)) { return this._MdIconRegistry_79; }
    if ((token === import33.MdSnackBar)) { return this._MdSnackBar_80; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_81; }
    if ((token === import96.LocationStrategy)) { return this._LocationStrategy_82; }
    if ((token === import64.Location)) { return this._Location_83; }
    if ((token === import65.UrlSerializer)) { return this._UrlSerializer_84; }
    if ((token === import66.RouterOutletMap)) { return this._RouterOutletMap_85; }
    if ((token === import116.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_86; }
    if ((token === import117.ROUTES)) { return this._ROUTES_87; }
    if ((token === import104.Router)) { return this._Router_88; }
    if ((token === import118.ActivatedRoute)) { return this._ActivatedRoute_89; }
    if ((token === import89.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_90; }
    if ((token === import68.AuthService)) { return this._AuthService_91; }
    if ((token === import69.QuestionService)) { return this._QuestionService_92; }
    if ((token === import70.GameListServices)) { return this._GameListServices_93; }
    if ((token === import71.SocketService)) { return this._SocketService_94; }
    if ((token === import72.OpponentFindService)) { return this._OpponentFindService_95; }
    if ((token === import73.ArenaServices)) { return this._ArenaServices_96; }
    if ((token === import74.QuestionServices)) { return this._QuestionServices_97; }
    if ((token === import75.QuestionAnswerServices)) { return this._QuestionAnswerServices_98; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__44.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);